### PR TITLE
Fix scale up with no assigned node

### LINKED ISSUE #465: autoscaler does not consider whether pod can schedule to node causing pending status
I'm running case1 in https://github.com/PaddlePaddle/cloud/issues/399

```
Non-terminated Pods:		(6 in total)
  Namespace			Name				CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----				------------	----------	---------------	-------------
  kube-system			calico-node-qzn36		250m (2%)	0 (0%)		0 (0%)		0 (0%)
  wuyi05-baidu-com		mnist14-trainer-k22dp		2 (16%)		3 (25%)		8Gi (8%)	8Gi (8%)
  wuyi05-baidu-com		mnist15-trainer-z4s0r		2 (16%)		3 (25%)		8Gi (8%)	8Gi (8%)
  wuyi05-baidu-com		mnist17-trainer-wqrpz		2 (16%)		3 (25%)		8Gi (8%)	8Gi (8%)
  wuyi05-baidu-com		mnist5-pserver-fk552		2 (16%)		3 (25%)		5Gi (5%)	5Gi (5%)
  wuyi05-baidu-com		mnist9-pserver-vb1nz		2 (16%)		3 (25%)		5Gi (5%)	5Gi (5%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  10250m (85%)	15 (125%)	34Gi (36%)	34Gi (36%)
```

node CPU Request is 10250m and pod request 2 cores (2000m), autoscaler is still scaling up in this case.

### PR DESCRIPTION
**Pull request by Yancey1989**
Fixed #465

### CODE REVIEW

File: go/controller/cluster.go [hunk 1]
```diff
@@ -95,6 +95,26 @@ func getPodsTotalRequestsAndLimits(podList *v1.PodList) (reqs v1.ResourceList, l
 	return
 }
 
+func syncNodesIdleResource(podList *v1.PodList, nodesCPUIdleMilli map[string]int64, nodesMemoryIdleMega map[string]int64) (err error) {
+	for _, pod := range podList.Items {
+		nodeName := pod.Spec.NodeName
+		// if nodeName is empty, the pod is not assigned.
```
Comment (typhoonzero) [inline go/controller/cluster.go]: This comment seems not needed, the below code is clear enough.

File: go/autoscaler/autoscaler.go [hunk 2]
```diff
@@ -282,6 +309,11 @@ func scaleDryRun(r *ClusterResource, j job, curDiff int, maxLoadDesired float64,
 		return
 	}
 
+	if !searchAssignableNodeByCPU(r, j) || !searchAssignableNodeByMem(r, j) {
+		// can not find assignable node, do not scale
+		additional = 0
```
Comment (typhoonzero) [inline go/autoscaler/autoscaler.go]: Need to return immediately from here, or else the code below may be executed.

File: go/autoscaler/autoscaler.go [hunk 3]
```diff
@@ -222,6 +225,30 @@ nextJob:
 	return js
 }
 
+func searchAssignableNodeByCPU(r *ClusterResource, j job) (assignable bool) {
+	assignable = false
+	for _, idle := range r.NodesCPUIdleMilli {
+		if j.TrainerCPURequestMilli() <= idle {
+			assignable = true
```
Comment (typhoonzero) [inline go/autoscaler/autoscaler.go]: In go, if return value is declared with a var name, `return` will return the var name directly, this is useful when we need to declare the return value at the begining of the function, like `var ret bool`.

In your case, just define return type `bool` and `return false` or `return true` will do the job.

File: go/controller/cluster.go [hunk 4]
```diff
@@ -143,7 +175,9 @@ func (c *Cluster) SyncResource() (res autoscaler.ClusterResource, err error) {
 		GPULimit:        int(allLimits.NvidiaGPU().Value()),
 		CPULimitMilli:   allLimits.Cpu().ScaledValue(resource.Milli),
 		MemoryLimitMega: allLimits.Memory().ScaledValue(resource.Mega),
-	}
 
+		NodesCPUIdleMilli:   nodesCPUIdleMilli,
+		NodesMemoryIdleMega: nodesMemoryIdleMega,
```
Comment (typhoonzero) [inline go/controller/cluster.go]: We say idle cpu and free memory, not idle memory.

File: go/autoscaler/autoscaler.go (hunk 2 above)
Comment (Yancey1989) [reply go/autoscaler/autoscaler.go]: Done.

File: go/controller/cluster.go (hunk 1 above)
Comment (Yancey1989) [reply go/controller/cluster.go]: Done.

File: go/controller/cluster.go (hunk 4 above)
Comment (Yancey1989) [reply go/controller/cluster.go]: Done.

File: go/autoscaler/autoscaler.go (hunk 3 above)
Comment (Yancey1989) [reply go/autoscaler/autoscaler.go]: Thanks, got it. Done.

File: go/controller/cluster.go [hunk 5]
```diff
@@ -95,6 +95,25 @@ func getPodsTotalRequestsAndLimits(podList *v1.PodList) (reqs v1.ResourceList, l
 	return
 }
 
+func syncNodesIdleResource(podList *v1.PodList, nodesCPUIdleMilli map[string]int64, nodesMemoryFreeMega map[string]int64) (err error) {
+	for _, pod := range podList.Items {
+		nodeName := pod.Spec.NodeName
+		if nodeName == "" {
+			continue
+		}
+		for _, container := range pod.Spec.Containers {
```
Comment (helinwang) [inline go/controller/cluster.go]: Should we check only pending and running pods?

Comment (Yancey1989) [reply go/controller/cluster.go]: Only Terminating and Running Pod will take up the resource.

Comment (helinwang) [reply go/controller/cluster.go]: Oh ok, so maybe we need to check only "Terminating and Running" pod? :)

Comment (Yancey1989) [reply go/controller/cluster.go]: I think so, follow the comment https://github.com/kubernetes/kubernetes/blob/v1.6.2/pkg/api/v1/types.go#L2331, if `NodeName` is non-empty, the Pod will be assigned to the Node, mean take up the resuore on the Node.

Comment (helinwang) [reply go/controller/cluster.go]: I see, so it's not necessary to check pod status, since as long as `pod.Spec.NodeName` is not empty, it's assigned to a node, and occupying resource.

**Comment by helinwang** [comment]
LGTM after the test passes.

File: go/autoscaler/autoscaler.go [hunk 6]
```diff
@@ -505,7 +498,9 @@ func (a *Autoscaler) Monitor() {
 					continue
 				}
 				j.TrainerJob = tj
+				a.jobs[key] = j
```
Comment (helinwang) [inline go/autoscaler/autoscaler.go]: Need to write back to the map, `j.TrainerJob = tj` is not sufficient.

Comment (typhoonzero) [reply go/autoscaler/autoscaler.go]: Refine the code later is fine. Also, the scaling algorithm should be updated like: 

1. `ScaleDryRun` search in order to find a sufficient node to scale up 1 pod, return the diff.
1. Cluster total resource is *not* used for the scale-up, use only per node resource.
1. Find a way to ensure `max_load_desired` for each node.

Comment (helinwang) [reply go/autoscaler/autoscaler.go]: Thanks!

Btw, maybe `max_load_desired` is for the entire cluster? Otherwise if it's for each node on max_load_desired=0.97, each node will have 0.03*12=0.36 CPUs, probably many pod can not be scheduled on it anyway.
